title: Page
pages: true
files: true
  fields:
    caption:
      label: Caption
      type: textarea
    credit:
      label: Credit
      type: text
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
