title: Page
pages: true
files: true
  fields:
    description:
      label: Description
      type: text
    credit:
      label: Credit
      type: textarea
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
