title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  subtitle:
    label: Subtitle
    type: text
  ongoing:
    label: Archived?
    type: toggle
    width: 1/3
  tags:
    label: Tags
    type:  tags
  builder:
    label: Sections
    type: builder
    fieldsets:
      bodytext:
        label: Body Text
        snippet: sections/bodytext
        fields:
          text:
            label: Text
            type: textarea
      quote:
        label: Quote
        snippet: sections/quote
        fields:
          text:
            label: Quote Text
            type: textarea
          citation:
            label: Citation
            type: text
      excerpt:
        label: Excerpt
        snippet: sections/excerpt
        fields:
          text:
            label: Quote Text
            type: textarea
          title:
            label: Title
            type: text
            width: 1/2
          link:
            label: Link
            type: url
            width: 1/2
          date_text:
            label: Date
            type: text
