title: Project
pages: false
files:
  sortable: true
  fields:
    description:
      label: Description
      type: text
    credit:
      label: Credit
      type: textarea
fields:
  title:
    label: Title
    type:  text
  subtitle:
    label: Subtitle
    type: text
  ongoing:
    label: Archived?
    type: toggle
    width: 1/3
  tags:
    label: Tags
    type:  tags
  builder: builder
