title: Project
pages: false
files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea
    credit:
      label: Credit
      type: textarea
fields:
  title:
    label: Title
    type:  text
  subtitle:
    label: Subtitle
    type: text
  disc:
    label: Disc
    type: image
    width: 1/3
  background:
    label: Background
    type: image
    width: 1/3
  foreground:
    label: Foreground
    type: image
    width: 1/3
  bannerbackground:
    label: Banner Background
    type: image
    width: 1/3
  bannerforeground:
    label: Banner Foreground
    type: image
    width: 1/3
  color:
    label: Color
    type: text
    width: 1/3
  sections:
    label: sections
    type: multiselect
    options: query
    query:
      page: sections
      fetch: children
      value: '{{title}}'
      text: '{{title}}'
      flip: true
    width: 1/2
  tags:
    label: Tags
    type:  tags
    width: 1/2
  builder: builder
