title: Project
pages: false
files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea
    credit:
      label: Credit
      type: textarea
fields:
  title:
    label: Title
    type:  text
  subtitle:
    label: Subtitle
    type: text
  icon:
    label: Icon
    type: image
    width: 1/3
  banner:
    label: Banner
    type: image
    width: 1/3
  color:
    label: Color
    type: colorlist
    width: 1/3
    options:
      - "#b07d7e"
      - "#daa863"
      - "#697ca1"
      - "#c4a4aa"
      - "#ca8989"
      - "#81a9b1"
      - "#d4c17e"
  sections:
    label: sections
    type: multiselect
    options: query
    query:
      page: sections
      fetch: children
      value: '{{title}}'
      text: '{{title}}'
      flip: true
    width: 1/2
  tags:
    label: Tags
    type:  tags
    width: 1/2
  builder: builder
