title: Project
pages: false
files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea
    credit:
      label: Credit
      type: textarea
fields:
  title:
    label: Title
    type:  text
  subtitle:
    label: Subtitle
    type: text
  themes:
    label: Themes
    type: multiselect
    options: query
    query:
      page: themes
      fetch: children
      value: '{{title}}'
      text: '{{title}}'
      flip: true
    width: 1/2
  tags:
    label: Tags
    type:  tags
    width: 1/2
  builder: builder
