title: Project
pages: false
files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea
    credit:
      label: Credit
      type: textarea
fields:
  title:
    label: Title
    type:  text
  subtitle:
    label: Subtitle
    type: text
  color:
    label: Color
    type: colorlist
    options:
      - "#eb1717"
      - "#28db78"
      - "#333333"
      - "#e74c3c"
      - "#353a62"
      - "#9b59b6"
      - "#d45353"
      - "#ffd041"
      - "#e91e63"
  sections:
    label: sections
    type: multiselect
    options: query
    query:
      page: sections
      fetch: children
      value: '{{title}}'
      text: '{{title}}'
      flip: true
    width: 1/2
  tags:
    label: Tags
    type:  tags
    width: 1/2
  builder: builder
